#!/bin/bash

# Create and use a new builder instance
docker buildx create --name multiarch --use

# Build the multi-platform image using the pre-built application
docker buildx build . -t $IMAGE_NAME --platform linux/amd64,linux/arm64/v8 --push
